[workspace]
resolver = "2"
members = [
    "aoc",
    "day01",
]

[workspace.package]
edition = "2021"

[workspace.dependencies]
aoc = { path = "./aoc"}

arrow = "53.3"
tokio = {version = "1", features = ["full"]}
