[package]
name = "day01"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc.workspace = true
arrow.workspace = true
arrow-array.workspace = true
arrow-schema.workspace = true
datafusion.workspace = true
plex.workspace = true
tokio.workspace = true